# Generated by Django 2.0.2 on 2018-05-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('startDate', models.DateTimeField(verbose_name='date published')),
                ('title', models.CharField(max_length=250)),
                ('article', models.TextField()),
            ],
        ),
    ]
