# Generated by Django 2.0.2 on 2018-05-25 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='user_name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
